# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20181123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Completed'), (3, 'Declined'), (4, 'Cancelled')], max_length=1),
        ),
    ]
