# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20181124_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='declined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
